# Generated by Django 3.1.5 on 2021-01-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('usu_eh_professor',)},
        ),
        migrations.RemoveField(
            model_name='sala',
            name='owner',
        ),
    ]
